# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'fast-news-ios' do

# pod 'RealmSwift'
pod 'CocoaSPDY'
pod 'ChameleonFramework'

end


