# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'fast-news-ios' do

pod 'CocoaSPDY'
pod 'ChameleonFramework'
pod 'SloppySwiper'
pod 'GradientView'
pod 'Shimmer'
pod 'AsyncDisplayKit'
pod 'ARCollectionViewMasonryLayout'

end


